## Detections classes:
0 - not climate change-related <br>
1 - climate change-related

# ClimateBert Climate Detector model - text classification task

### dataset load

In [2]:
!pip install transformers==4.28.0
!pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 63.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 236.8/236.8 kB 32.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 101.9 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.6/485.6 kB 12.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 kB 15.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.5/212.5 kB 21.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.3/134.3 kB 19.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 34.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.5/114.5 kB 15.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 18.3 MB/s eta 0:00:

### testing the climate detection test dataset on the climate detection model

In [3]:
from datasets import load_dataset
climate_detection_dataset = load_dataset("climatebert/climate_detection")

Extracting data files:   0%|          | 0/2 [00:00<?, ?it/s]

Generating train split:   0%|          | 0/1300 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/400 [00:00<?, ? examples/s]

Dataset parquet downloaded and prepared to /root/.cache/huggingface/datasets/climatebert___parquet/climatebert--climate_detection-eefa7af3c8031d26/0.0.0/14a00e99c0d15a23649d0db8944380ac81082d4b021f398733dd84f3a6c569a7. Subsequent calls will reuse this data.


  0%|          | 0/2 [00:00<?, ?it/s]

### model loading

In [4]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

climate_change_tokenizer = AutoTokenizer.from_pretrained("climatebert/distilroberta-base-climate-detector")

climate_change_model = AutoModelForSequenceClassification.from_pretrained("climatebert/distilroberta-base-climate-detector")

In [5]:
climate_detection_encoded_dataset = climate_detection_dataset.map(lambda t: climate_change_tokenizer(t['text'],  truncation=True), batched=True,load_from_cache_file=False)

Map:   0%|          | 0/1300 [00:00<?, ? examples/s]

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

In [6]:
from transformers import TrainingArguments, Trainer

In [7]:
climate_change_arg = TrainingArguments(
    "label",
    learning_rate=5e-5,
    num_train_epochs=4,
    per_device_eval_batch_size=32,
    per_device_train_batch_size=32,
    seed=19
)

In [8]:
climate_change_trainer = Trainer(
    model=climate_change_model,
    args=climate_change_arg,
    tokenizer=climate_change_tokenizer,
    eval_dataset=climate_detection_encoded_dataset['test']
)

In [9]:
y_pred_climate_change = climate_change_trainer.predict(climate_detection_encoded_dataset['test'])

You're using a RobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


In [10]:
y_pred_climate_change = y_pred_climate_change.predictions

In [11]:
import numpy as np
y_pred_climate_change = [np.argmax(y_pred_climate_change[i]) for i in range(0,len(y_pred_climate_change))]

In [12]:
y_pred_climate_change

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,


In [13]:
from sklearn.metrics import classification_report,f1_score,confusion_matrix
print(f1_score(climate_detection_encoded_dataset['test']['label'],y_pred_climate_change,average='macro'))

0.9572313105687265


In [14]:
print(classification_report(climate_detection_encoded_dataset['test']['label'],y_pred_climate_change))

              precision    recall  f1-score   support

           0       0.93      0.94      0.93        80
           1       0.98      0.98      0.98       320

    accuracy                           0.97       400
   macro avg       0.96      0.96      0.96       400
weighted avg       0.97      0.97      0.97       400



In [15]:
print(confusion_matrix(climate_detection_encoded_dataset['test']['label'], y_pred_climate_change))

[[ 75   5]
 [  6 314]]


# Our Climate Change model - text classification task

### dataset load

In [16]:
!pip install transformers==4.28.0
!pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


### testing the climate detection test dataset on the climate detection model

In [17]:
from datasets import load_dataset
climate_detection_dataset = load_dataset("climatebert/climate_detection")

  0%|          | 0/2 [00:00<?, ?it/s]

### model loading

In [18]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

climate_change_tokenizer = AutoTokenizer.from_pretrained("/content/drive/MyDrive/DS-Environment-Project/Models/climate-change-model-based-on-climate-detector-further-trained-on-paragraphs")

climate_change_model = AutoModelForSequenceClassification.from_pretrained("/content/drive/MyDrive/DS-Environment-Project/Models/climate-change-model-based-on-climate-detector-further-trained-on-paragraphs")

In [19]:
climate_detection_encoded_dataset = climate_detection_dataset.map(lambda t: climate_change_tokenizer(t['text'],  truncation=True), batched=True,load_from_cache_file=False)

Map:   0%|          | 0/1300 [00:00<?, ? examples/s]

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

In [20]:
from transformers import TrainingArguments, Trainer

In [21]:
climate_change_arg = TrainingArguments(
    "label",
    learning_rate=5e-5,
    num_train_epochs=4,
    per_device_eval_batch_size=32,
    per_device_train_batch_size=32,
    seed=19
)

In [22]:
climate_change_trainer = Trainer(
    model=climate_change_model,
    args=climate_change_arg,
    tokenizer=climate_change_tokenizer,
    eval_dataset=climate_detection_encoded_dataset['test']
)

In [23]:
y_pred_climate_change = climate_change_trainer.predict(climate_detection_encoded_dataset['test'])

You're using a RobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


In [24]:
y_pred_climate_change = y_pred_climate_change.predictions

In [25]:
import numpy as np
y_pred_climate_change = [np.argmax(y_pred_climate_change[i]) for i in range(0,len(y_pred_climate_change))]

In [26]:
y_pred_climate_change

[1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,


In [27]:
from sklearn.metrics import classification_report,f1_score,confusion_matrix
print(f1_score(climate_detection_encoded_dataset['test']['label'],y_pred_climate_change,average='macro'))

0.9326405880080435


In [28]:
print(classification_report(climate_detection_encoded_dataset['test']['label'],y_pred_climate_change))

              precision    recall  f1-score   support

           0       0.91      0.88      0.89        80
           1       0.97      0.98      0.97       320

    accuracy                           0.96       400
   macro avg       0.94      0.93      0.93       400
weighted avg       0.96      0.96      0.96       400



In [29]:
print(confusion_matrix(climate_detection_encoded_dataset['test']['label'], y_pred_climate_change))

[[ 70  10]
 [  7 313]]


# Sentiment classes:
0 - risk <br>
1 - neutral <br>
2 - opportunity

# ClimateBert Climate Detector model - sentiment task

### dataset load

In [ ]:
!pip install transformers==4.28.0
!pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


### testing the climate detection test dataset on the climate detection model

In [ ]:
from datasets import load_dataset
climate_detection_dataset = load_dataset("climatebert/climate_sentiment")

Extracting data files:   0%|          | 0/2 [00:00<?, ?it/s]

Generating train split:   0%|          | 0/1000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/320 [00:00<?, ? examples/s]

Dataset parquet downloaded and prepared to /root/.cache/huggingface/datasets/climatebert___parquet/climatebert--climate_sentiment-cde94fbdb0f4004a/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec. Subsequent calls will reuse this data.


  0%|          | 0/2 [00:00<?, ?it/s]

### model loading

In [ ]:
# from transformers import AutoTokenizer, AutoModelForSequenceClassification

# climate_change_tokenizer = AutoTokenizer.from_pretrained("climatebert/distilroberta-base-climate-sentiment")

# climate_change_model = AutoModelForSequenceClassification.from_pretrained("climatebert/distilroberta-base-climate-sentiment")

In [ ]:
climate_detection_encoded_dataset = climate_detection_dataset.map(lambda t: climate_change_tokenizer(t['text'],  truncation=True), batched=True,load_from_cache_file=False)

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

Map:   0%|          | 0/320 [00:00<?, ? examples/s]

In [ ]:
# from transformers import TrainingArguments, Trainer

In [ ]:
# climate_change_arg = TrainingArguments(
#     "label",
#     learning_rate=5e-5,
#     num_train_epochs=4,
#     per_device_eval_batch_size=32,
#     per_device_train_batch_size=32,
#     seed=19
# )

In [ ]:
# climate_change_trainer = Trainer(
#     model=climate_change_model,
#     args=climate_change_arg,
#     tokenizer=climate_change_tokenizer,
#     eval_dataset=climate_detection_encoded_dataset['test']
# )

In [ ]:
# y_pred_climate_change = climate_change_trainer.predict(climate_detection_encoded_dataset['test'])

You're using a RobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


In [ ]:
# y_pred_climate_change = y_pred_climate_change.predictions

In [ ]:
# import numpy as np
# y_pred_climate_change = [np.argmax(y_pred_climate_change[i]) for i in range(0,len(y_pred_climate_change))]

In [ ]:
# y_pred_climate_change

[1,
 2,
 0,
 2,
 2,
 0,
 2,
 1,
 1,
 2,
 1,
 0,
 0,
 1,
 2,
 2,
 2,
 0,
 2,
 1,
 2,
 2,
 1,
 0,
 1,
 2,
 2,
 2,
 1,
 2,
 1,
 1,
 0,
 1,
 2,
 0,
 2,
 1,
 0,
 0,
 0,
 1,
 2,
 1,
 0,
 2,
 1,
 1,
 2,
 0,
 0,
 2,
 1,
 1,
 1,
 0,
 0,
 2,
 2,
 1,
 2,
 0,
 2,
 2,
 2,
 1,
 2,
 0,
 1,
 2,
 2,
 2,
 1,
 1,
 0,
 1,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 2,
 1,
 1,
 2,
 0,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 0,
 1,
 0,
 2,
 2,
 2,
 1,
 0,
 1,
 1,
 0,
 1,
 2,
 1,
 0,
 0,
 2,
 2,
 2,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 2,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 2,
 0,
 2,
 0,
 0,
 2,
 2,
 0,
 1,
 0,
 0,
 1,
 2,
 0,
 2,
 2,
 1,
 1,
 2,
 0,
 2,
 0,
 0,
 1,
 2,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 0,
 1,
 2,
 0,
 2,
 0,
 1,
 1,
 0,
 1,
 0,
 2,
 0,
 2,
 1,
 1,
 1,
 2,
 0,
 1,
 2,
 1,
 1,
 2,
 1,
 0,
 1,
 2,
 0,
 2,
 0,
 2,
 2,
 1,
 1,
 0,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 0,
 0,
 1,
 1,
 0,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 0,
 0,
 1,
 1,
 0,
 2,
 2,


In [ ]:
# from sklearn.metrics import classification_report,f1_score,confusion_matrix
# print(f1_score(climate_detection_encoded_dataset['test']['label'],y_pred_climate_change,average='macro'))

0.28619873670088875


In [ ]:
# print(classification_report(climate_detection_encoded_dataset['test']['label'],y_pred_climate_change))

              precision    recall  f1-score   support

           0       0.07      0.06      0.06       106
           1       0.92      0.70      0.79       163
           2       0.00      0.00      0.00        51

    accuracy                           0.38       320
   macro avg       0.33      0.25      0.29       320
weighted avg       0.49      0.38      0.43       320



In [ ]:
# print(confusion_matrix(climate_detection_encoded_dataset['test']['label'], y_pred_climate_change))

[[  6   5  95]
 [ 29 114  20]
 [ 46   5   0]]


### evaluation


In [ ]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer, pipeline
from transformers.pipelines.pt_utils import KeyDataset
import datasets
from tqdm.auto import tqdm
dataset_name = "climatebert/climate_sentiment"
model_name = "climatebert/distilroberta-base-climate-sentiment"
results_list = []
# If you want to use your own data, simply load them as 🤗 Datasets dataset, see https://huggingface.co/docs/datasets/loading
dataset = datasets.load_dataset(dataset_name, split="test")

model = AutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name, max_len=512)

pipe = pipeline("text-classification", model=model, tokenizer=tokenizer, device=0)

# See https://huggingface.co/docs/transformers/main_classes/pipelines#transformers.pipeline
for out in tqdm(pipe(KeyDataset(dataset, "text"), padding=True, truncation=True)):
   print(out)
   results_list.append(out['label'])

  0%|          | 0/320 [00:00<?, ?it/s]

{'label': 'neutral', 'score': 0.5521345734596252}
{'label': 'risk', 'score': 0.7114208340644836}
{'label': 'opportunity', 'score': 0.527575671672821}
{'label': 'risk', 'score': 0.8287062644958496}
{'label': 'risk', 'score': 0.9858821630477905}
{'label': 'opportunity', 'score': 0.9299161434173584}
{'label': 'risk', 'score': 0.9891158938407898}
{'label': 'neutral', 'score': 0.968910276889801}
{'label': 'neutral', 'score': 0.9250478744506836}
{'label': 'risk', 'score': 0.9823044538497925}
{'label': 'neutral', 'score': 0.9688105583190918}
{'label': 'opportunity', 'score': 0.9198002815246582}
{'label': 'opportunity', 'score': 0.8694443702697754}
{'label': 'neutral', 'score': 0.959088921546936}
{'label': 'risk', 'score': 0.9896414875984192}
{'label': 'risk', 'score': 0.9681720733642578}
{'label': 'risk', 'score': 0.9695484638214111}
{'label': 'opportunity', 'score': 0.8578444719314575}
{'label': 'risk', 'score': 0.9158833622932434}
{'label': 'neutral', 'score': 0.9607136845588684}
{'label': 

In [ ]:
results_list

['neutral',
 'risk',
 'opportunity',
 'risk',
 'risk',
 'opportunity',
 'risk',
 'neutral',
 'neutral',
 'risk',
 'neutral',
 'opportunity',
 'opportunity',
 'neutral',
 'risk',
 'risk',
 'risk',
 'opportunity',
 'risk',
 'neutral',
 'risk',
 'risk',
 'neutral',
 'opportunity',
 'neutral',
 'risk',
 'risk',
 'risk',
 'neutral',
 'risk',
 'neutral',
 'neutral',
 'opportunity',
 'neutral',
 'risk',
 'opportunity',
 'risk',
 'neutral',
 'opportunity',
 'opportunity',
 'opportunity',
 'neutral',
 'risk',
 'neutral',
 'opportunity',
 'risk',
 'neutral',
 'neutral',
 'risk',
 'opportunity',
 'opportunity',
 'risk',
 'neutral',
 'neutral',
 'neutral',
 'opportunity',
 'opportunity',
 'risk',
 'risk',
 'neutral',
 'risk',
 'opportunity',
 'risk',
 'risk',
 'risk',
 'neutral',
 'risk',
 'opportunity',
 'neutral',
 'risk',
 'risk',
 'risk',
 'neutral',
 'neutral',
 'opportunity',
 'neutral',
 'risk',
 'opportunity',
 'risk',
 'risk',
 'risk',
 'risk',
 'risk',
 'neutral',
 'opportunity',
 'neutr

In [ ]:
preds = []
for result in results_list:
  if result == 'risk':
    preds.append(0)
  elif result == 'neutral':
    preds.append(1)
  else:
    preds.append(2)


In [ ]:
preds

[1,
 0,
 2,
 0,
 0,
 2,
 0,
 1,
 1,
 0,
 1,
 2,
 2,
 1,
 0,
 0,
 0,
 2,
 0,
 1,
 0,
 0,
 1,
 2,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 2,
 1,
 0,
 2,
 0,
 1,
 2,
 2,
 2,
 1,
 0,
 1,
 2,
 0,
 1,
 1,
 0,
 2,
 2,
 0,
 1,
 1,
 1,
 2,
 2,
 0,
 0,
 1,
 0,
 2,
 0,
 0,
 0,
 1,
 0,
 2,
 1,
 0,
 0,
 0,
 1,
 1,
 2,
 1,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 0,
 1,
 1,
 0,
 2,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 2,
 1,
 2,
 0,
 0,
 0,
 1,
 2,
 1,
 1,
 2,
 1,
 0,
 1,
 2,
 2,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 0,
 2,
 0,
 2,
 2,
 0,
 0,
 2,
 1,
 2,
 2,
 1,
 0,
 2,
 0,
 0,
 1,
 1,
 0,
 2,
 0,
 2,
 2,
 1,
 0,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 2,
 1,
 0,
 2,
 0,
 2,
 1,
 1,
 2,
 1,
 2,
 0,
 2,
 0,
 1,
 1,
 1,
 0,
 2,
 1,
 0,
 1,
 1,
 0,
 1,
 2,
 1,
 0,
 2,
 0,
 2,
 0,
 0,
 1,
 1,
 2,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 2,
 2,
 1,
 1,
 2,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 2,
 2,
 1,
 1,
 2,
 0,
 0,


In [ ]:
from sklearn.metrics import classification_report,f1_score,confusion_matrix
print(f1_score(climate_detection_encoded_dataset['test']['label'],preds,average='macro'))

0.7837077636216803


In [ ]:
print(classification_report(climate_detection_encoded_dataset['test']['label'],preds))

              precision    recall  f1-score   support

           0       0.83      0.90      0.86       106
           1       0.92      0.70      0.79       163
           2       0.57      0.90      0.70        51

    accuracy                           0.80       320
   macro avg       0.77      0.83      0.78       320
weighted avg       0.83      0.80      0.80       320



In [ ]:
print(confusion_matrix(climate_detection_encoded_dataset['test']['label'], preds))

[[ 95   5   6]
 [ 20 114  29]
 [  0   5  46]]


# Our Climate Change model - sentiment task

### dataset load

In [ ]:
!pip install transformers==4.28.0
!pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


### testing the climate detection test dataset on the climate detection model

In [ ]:
from datasets import load_dataset
climate_detection_dataset = load_dataset("climatebert/climate_sentiment")

  0%|          | 0/2 [00:00<?, ?it/s]

### model loading

In [ ]:
# from transformers import AutoTokenizer, AutoModelForSequenceClassification

# climate_change_tokenizer = AutoTokenizer.from_pretrained("/content/drive/MyDrive/DS-Environment-Project/Models/climate-change-model-based-on-climate-detector-further-trained-on-paragraphs")

# climate_change_model = AutoModelForSequenceClassification.from_pretrained("/content/drive/MyDrive/DS-Environment-Project/Models/climate-change-model-based-on-climate-detector-further-trained-on-paragraphs")

In [ ]:
climate_detection_encoded_dataset = climate_detection_dataset.map(lambda t: climate_change_tokenizer(t['text'],  truncation=True), batched=True,load_from_cache_file=False)

Map:   0%|          | 0/1300 [00:00<?, ? examples/s]

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

In [ ]:
# from transformers import TrainingArguments, Trainer

In [ ]:
# climate_change_arg = TrainingArguments(
#     "label",
#     learning_rate=5e-5,
#     num_train_epochs=4,
#     per_device_eval_batch_size=32,
#     per_device_train_batch_size=32,
#     seed=19
# )

In [ ]:
# climate_change_trainer = Trainer(
#     model=climate_change_model,
#     args=climate_change_arg,
#     tokenizer=climate_change_tokenizer,
#     eval_dataset=climate_detection_encoded_dataset['test']
# )

In [ ]:
# y_pred_climate_change = climate_change_trainer.predict(climate_detection_encoded_dataset['test'])

You're using a RobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


In [ ]:
# y_pred_climate_change = y_pred_climate_change.predictions

In [ ]:
# import numpy as np
# y_pred_climate_change = [np.argmax(y_pred_climate_change[i]) for i in range(0,len(y_pred_climate_change))]

In [ ]:
# y_pred_climate_change

[1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,


In [ ]:
# from sklearn.metrics import classification_report,f1_score,confusion_matrix
# print(f1_score(climate_detection_encoded_dataset['test']['label'],y_pred_climate_change))

0.973561430793157


In [ ]:
# print(classification_report(climate_detection_encoded_dataset['test']['label'],y_pred_climate_change))

              precision    recall  f1-score   support

           0       0.91      0.88      0.89        80
           1       0.97      0.98      0.97       320

    accuracy                           0.96       400
   macro avg       0.94      0.93      0.93       400
weighted avg       0.96      0.96      0.96       400



In [ ]:
# print(confusion_matrix(climate_detection_encoded_dataset['test']['label'], y_pred_climate_change))

[[ 70  10]
 [  7 313]]


### evaluation


In [ ]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer, pipeline
from transformers.pipelines.pt_utils import KeyDataset
import datasets
from tqdm.auto import tqdm
dataset_name = "climatebert/climate_sentiment"
model_name = "c/content/drive/MyDrive/DS-Environment-Project/Models/climate-change-model-based-on-climate-detector-further-trained-on-paragraphs"
results_list = []
# If you want to use your own data, simply load them as 🤗 Datasets dataset, see https://huggingface.co/docs/datasets/loading
dataset = datasets.load_dataset(dataset_name, split="test")
tokenizer = AutoTokenizer.from_pretrained("/content/drive/MyDrive/DS-Environment-Project/Models/climate-change-model-based-on-climate-detector-further-trained-on-paragraphs",max_len=512)

model = AutoModelForSequenceClassification.from_pretrained("/content/drive/MyDrive/DS-Environment-Project/Models/climate-change-model-based-on-climate-detector-further-trained-on-paragraphs", num_labels=3,ignore_mismatched_sizes=True)



pipe = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer, device=0)

# See https://huggingface.co/docs/transformers/main_classes/pipelines#transformers.pipeline
for out in tqdm(pipe(KeyDataset(dataset, "text"), padding=True, truncation=True, )):
   print(out)
   results_list.append(out['label'])

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at /content/drive/MyDrive/DS-Environment-Project/Models/climate-change-model-based-on-climate-detector-further-trained-on-paragraphs and are newly initialized because the shapes did not match:
- classifier.out_proj.weight: found shape torch.Size([2, 768]) in the checkpoint and torch.Size([3, 768]) in the model instantiated
- classifier.out_proj.bias: found shape torch.Size([2]) in the checkpoint and torch.Size([3]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


  0%|          | 0/320 [00:00<?, ?it/s]

{'label': 'LABEL_2', 'score': 0.3887050151824951}
{'label': 'LABEL_0', 'score': 0.3635159432888031}
{'label': 'LABEL_0', 'score': 0.3679000735282898}
{'label': 'LABEL_2', 'score': 0.3726438581943512}
{'label': 'LABEL_0', 'score': 0.37816646695137024}
{'label': 'LABEL_0', 'score': 0.3709317743778229}
{'label': 'LABEL_0', 'score': 0.3767683804035187}
{'label': 'LABEL_0', 'score': 0.370037704706192}
{'label': 'LABEL_0', 'score': 0.37231141328811646}
{'label': 'LABEL_0', 'score': 0.36192408204078674}
{'label': 'LABEL_0', 'score': 0.3601401448249817}
{'label': 'LABEL_0', 'score': 0.35999196767807007}
{'label': 'LABEL_0', 'score': 0.3571297228336334}
{'label': 'LABEL_0', 'score': 0.3617800176143646}
{'label': 'LABEL_0', 'score': 0.37679818272590637}
{'label': 'LABEL_2', 'score': 0.37971779704093933}
{'label': 'LABEL_2', 'score': 0.356721431016922}
{'label': 'LABEL_2', 'score': 0.4225902259349823}
{'label': 'LABEL_0', 'score': 0.3764422535896301}
{'label': 'LABEL_0', 'score': 0.35907670855522

In [ ]:
results_list

['LABEL_2',
 'LABEL_0',
 'LABEL_0',
 'LABEL_2',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_2',
 'LABEL_2',
 'LABEL_2',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_2',
 'LABEL_2',
 'LABEL_0',
 'LABEL_2',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_2',
 'LABEL_0',
 'LABEL_2',
 'LABEL_0',
 'LABEL_0',
 'LABEL_2',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_2',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_2',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_2',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_2',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LABEL_0',
 'LA

In [ ]:
preds = []
for result in results_list:
  if result == 'LABEL_0':
    preds.append(0)
  elif result == 'LABEL_1':
    preds.append(1)
  else:
    preds.append(2)


In [ ]:
preds

[2,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 2,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 2,
 2,
 0,
 0,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 2,
 0,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 2,
 0,
 2,
 0,
 0,
 2,
 0,
 0,
 0,
 1,
 2,
 0,
 2,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 2,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 2,
 2,
 0,
 2,
 2,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 2,
 2,
 0,
 0,
 1,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 2,
 0,
 2,
 0,
 0,
 2,
 0,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [ ]:
from sklearn.metrics import classification_report,f1_score,confusion_matrix
print(f1_score(climate_detection_encoded_dataset['test']['label'],preds,average='macro'))

0.18587627498263604


In [ ]:
print(classification_report(climate_detection_encoded_dataset['test']['label'],preds))

              precision    recall  f1-score   support

           0       0.32      0.74      0.44       106
           1       0.00      0.00      0.00       163
           2       0.10      0.14      0.12        51

    accuracy                           0.27       320
   macro avg       0.14      0.29      0.19       320
weighted avg       0.12      0.27      0.16       320



In [ ]:
print(confusion_matrix(climate_detection_encoded_dataset['test']['label'], preds))

[[ 78   3  25]
 [125   0  38]
 [ 44   0   7]]


# Classes:
0 - is not about climate change commitment and actions <br>
1 - is about climate change commitment and actions <br>


# ClimateBert Climate Detector model - text is about climate change commitment and actions classification

### dataset load

In [ ]:
!pip install transformers==4.28.0
!pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


### testing the climate detection test dataset on the climate detection model

In [ ]:
from datasets import load_dataset
climate_detection_dataset = load_dataset("climatebert/climate_commitments_actions")

Extracting data files:   0%|          | 0/2 [00:00<?, ?it/s]

Generating train split:   0%|          | 0/1000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/320 [00:00<?, ? examples/s]

Dataset parquet downloaded and prepared to /root/.cache/huggingface/datasets/climatebert___parquet/climatebert--climate_commitments_actions-c39067b6628a5441/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec. Subsequent calls will reuse this data.


  0%|          | 0/2 [00:00<?, ?it/s]

### model loading

In [ ]:
climate_detection_encoded_dataset = climate_detection_dataset.map(lambda t: climate_change_tokenizer(t['text'],  truncation=True), batched=True,load_from_cache_file=False)

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

Map:   0%|          | 0/320 [00:00<?, ? examples/s]

### evaluation


In [ ]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer, pipeline
from transformers.pipelines.pt_utils import KeyDataset
import datasets
from tqdm.auto import tqdm
dataset_name = "climatebert/climate_commitments_actions"
model_name = "climatebert/distilroberta-base-climate-commitment"
results_list = []
# If you want to use your own data, simply load them as 🤗 Datasets dataset, see https://huggingface.co/docs/datasets/loading
dataset = datasets.load_dataset(dataset_name, split="test")

model = AutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name, max_len=512)

pipe = pipeline("text-classification", model=model, tokenizer=tokenizer, device=0)

# See https://huggingface.co/docs/transformers/main_classes/pipelines#transformers.pipeline
for out in tqdm(pipe(KeyDataset(dataset, "text"), padding=True, truncation=True)):
   print(out)
   results_list.append(out['label'])

  0%|          | 0/320 [00:00<?, ?it/s]

{'label': 'yes', 'score': 0.9893452525138855}
{'label': 'no', 'score': 0.9779637455940247}
{'label': 'yes', 'score': 0.983881950378418}
{'label': 'yes', 'score': 0.8403359055519104}
{'label': 'no', 'score': 0.9988310933113098}
{'label': 'yes', 'score': 0.9424760341644287}
{'label': 'no', 'score': 0.9993083477020264}
{'label': 'no', 'score': 0.9920903444290161}
{'label': 'yes', 'score': 0.6929238438606262}
{'label': 'no', 'score': 0.9990754127502441}
{'label': 'yes', 'score': 0.8207420110702515}
{'label': 'no', 'score': 0.6175103783607483}
{'label': 'yes', 'score': 0.9825687408447266}
{'label': 'no', 'score': 0.999211311340332}
{'label': 'no', 'score': 0.9992019534111023}
{'label': 'no', 'score': 0.9987655878067017}
{'label': 'no', 'score': 0.9989387392997742}
{'label': 'yes', 'score': 0.9567462801933289}
{'label': 'yes', 'score': 0.9971885085105896}
{'label': 'no', 'score': 0.9981558918952942}
{'label': 'no', 'score': 0.9983795881271362}
{'label': 'no', 'score': 0.9991758465766907}
{'l

In [ ]:
results_list

['yes',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'ye

In [ ]:
preds = []
for result in results_list:
  if result == 'no':
    preds.append(0)
  elif result == 'yes':
    preds.append(1)


In [ ]:
preds

[1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,


In [ ]:
from sklearn.metrics import classification_report,f1_score,confusion_matrix
print(f1_score(climate_detection_encoded_dataset['test']['label'],preds,average='macro'))

0.7979032461791082


In [ ]:
print(classification_report(climate_detection_encoded_dataset['test']['label'],preds))

              precision    recall  f1-score   support

           0       0.94      0.78      0.85       222
           1       0.64      0.89      0.74        98

    accuracy                           0.81       320
   macro avg       0.79      0.83      0.80       320
weighted avg       0.85      0.81      0.82       320



In [ ]:
print(confusion_matrix(climate_detection_encoded_dataset['test']['label'], preds))

[[173  49]
 [ 11  87]]


# Our Climate Change model - text is about climate change commitment and actions classification

### dataset load

In [ ]:
!pip install transformers==4.28.0
!pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


### testing the climate detection test dataset on the climate detection model

In [ ]:
from datasets import load_dataset
climate_detection_dataset = load_dataset("climatebert/climate_commitments_actions")

  0%|          | 0/2 [00:00<?, ?it/s]

### model loading

In [ ]:
# from transformers import AutoTokenizer, AutoModelForSequenceClassification

# climate_change_tokenizer = AutoTokenizer.from_pretrained("/content/drive/MyDrive/DS-Environment-Project/Models/climate-change-model-based-on-climate-detector-further-trained-on-paragraphs")

# climate_change_model = AutoModelForSequenceClassification.from_pretrained("/content/drive/MyDrive/DS-Environment-Project/Models/climate-change-model-based-on-climate-detector-further-trained-on-paragraphs")

In [ ]:
climate_detection_encoded_dataset = climate_detection_dataset.map(lambda t: climate_change_tokenizer(t['text'],  truncation=True), batched=True,load_from_cache_file=False)

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

Map:   0%|          | 0/320 [00:00<?, ? examples/s]

In [ ]:
# from transformers import TrainingArguments, Trainer

In [ ]:
# climate_change_arg = TrainingArguments(
#     "label",
#     learning_rate=5e-5,
#     num_train_epochs=4,
#     per_device_eval_batch_size=32,
#     per_device_train_batch_size=32,
#     seed=19
# )

In [ ]:
# climate_change_trainer = Trainer(
#     model=climate_change_model,
#     args=climate_change_arg,
#     tokenizer=climate_change_tokenizer,
#     eval_dataset=climate_detection_encoded_dataset['test']
# )

In [ ]:
# y_pred_climate_change = climate_change_trainer.predict(climate_detection_encoded_dataset['test'])

In [ ]:
# y_pred_climate_change = y_pred_climate_change.predictions

In [ ]:
# import numpy as np
# y_pred_climate_change = [np.argmax(y_pred_climate_change[i]) for i in range(0,len(y_pred_climate_change))]

In [ ]:
# y_pred_climate_change

### evaluation


In [ ]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer, pipeline
from transformers.pipelines.pt_utils import KeyDataset
import datasets
from tqdm.auto import tqdm
dataset_name = "climatebert/climate_commitments_actions"
model_name = "c/content/drive/MyDrive/DS-Environment-Project/Models/climate-change-model-based-on-climate-detector-further-trained-on-paragraphs"
results_list = []
# If you want to use your own data, simply load them as 🤗 Datasets dataset, see https://huggingface.co/docs/datasets/loading
dataset = datasets.load_dataset(dataset_name, split="test")
tokenizer = AutoTokenizer.from_pretrained("/content/drive/MyDrive/DS-Environment-Project/Models/climate-change-model-based-on-climate-detector-further-trained-on-paragraphs",max_len=512)

model = AutoModelForSequenceClassification.from_pretrained("/content/drive/MyDrive/DS-Environment-Project/Models/climate-change-model-based-on-climate-detector-further-trained-on-paragraphs")



pipe = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer, device=0)

# See https://huggingface.co/docs/transformers/main_classes/pipelines#transformers.pipeline
for out in tqdm(pipe(KeyDataset(dataset, "text"), padding=True, truncation=True, )):
   print(out)
   results_list.append(out['label'])

  0%|          | 0/320 [00:00<?, ?it/s]

{'label': 'yes', 'score': 0.9999566078186035}
{'label': 'yes', 'score': 0.9999780654907227}
{'label': 'yes', 'score': 0.9999781847000122}
{'label': 'no', 'score': 0.997946560382843}
{'label': 'yes', 'score': 0.999976634979248}
{'label': 'yes', 'score': 0.999977707862854}
{'label': 'yes', 'score': 0.9999772310256958}
{'label': 'yes', 'score': 0.9999786615371704}
{'label': 'yes', 'score': 0.9999775886535645}
{'label': 'yes', 'score': 0.9999761581420898}
{'label': 'yes', 'score': 0.9999780654907227}
{'label': 'yes', 'score': 0.9999768733978271}
{'label': 'yes', 'score': 0.999977707862854}
{'label': 'yes', 'score': 0.9999772310256958}
{'label': 'yes', 'score': 0.9999779462814331}
{'label': 'yes', 'score': 0.9999450445175171}
{'label': 'yes', 'score': 0.9999655485153198}
{'label': 'yes', 'score': 0.9984989166259766}
{'label': 'yes', 'score': 0.9999773502349854}
{'label': 'yes', 'score': 0.9999767541885376}
{'label': 'yes', 'score': 0.9999773502349854}
{'label': 'yes', 'score': 0.99997794628

In [ ]:
results_list

['yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 

In [ ]:
preds = []
for result in results_list:
  if result == 'no':
    preds.append(0)
  elif result == 'yes':
    preds.append(1)


In [ ]:
preds

[1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [ ]:
from sklearn.metrics import classification_report,f1_score,confusion_matrix
print(f1_score(climate_detection_encoded_dataset['test']['label'],preds,average='macro'))

0.2690105079739479


In [ ]:
print(classification_report(climate_detection_encoded_dataset['test']['label'],preds))

              precision    recall  f1-score   support

           0       1.00      0.03      0.06       222
           1       0.31      1.00      0.48        98

    accuracy                           0.33       320
   macro avg       0.66      0.52      0.27       320
weighted avg       0.79      0.33      0.19       320



In [ ]:
print(confusion_matrix(climate_detection_encoded_dataset['test']['label'], preds))

[[  7 215]
 [  0  98]]


# Specificity Classes:
0 - is not specific <br>
1 - is specific <br>


# ClimateBert Climate Detector model - identify whether a climate-related paragraph is specific or non-specific

### dataset load

In [ ]:
!pip install transformers==4.28.0
!pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


### testing the climate detection test dataset on the climate detection model

In [ ]:
from datasets import load_dataset
climate_detection_dataset = load_dataset("climatebert/climate_specificity")

Extracting data files:   0%|          | 0/2 [00:00<?, ?it/s]

Generating train split:   0%|          | 0/1000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/320 [00:00<?, ? examples/s]

Dataset parquet downloaded and prepared to /root/.cache/huggingface/datasets/climatebert___parquet/climatebert--climate_specificity-cc194c8c8abc022c/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec. Subsequent calls will reuse this data.


  0%|          | 0/2 [00:00<?, ?it/s]

### model loading

In [ ]:
climate_detection_encoded_dataset = climate_detection_dataset.map(lambda t: climate_change_tokenizer(t['text'],  truncation=True), batched=True,load_from_cache_file=False)

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

Map:   0%|          | 0/320 [00:00<?, ? examples/s]

### evaluation


In [ ]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer, pipeline
from transformers.pipelines.pt_utils import KeyDataset
import datasets
from tqdm.auto import tqdm
dataset_name = "climatebert/climate_specificity"
model_name = "climatebert/distilroberta-base-climate-specificity"
results_list = []
# If you want to use your own data, simply load them as 🤗 Datasets dataset, see https://huggingface.co/docs/datasets/loading
dataset = datasets.load_dataset(dataset_name, split="test")

model = AutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name, max_len=512)

pipe = pipeline("text-classification", model=model, tokenizer=tokenizer, device=0)

# See https://huggingface.co/docs/transformers/main_classes/pipelines#transformers.pipeline
for out in tqdm(pipe(KeyDataset(dataset, "text"), padding=True, truncation=True)):
   print(out)
   results_list.append(out['label'])

  0%|          | 0/320 [00:00<?, ?it/s]

{'label': 'non', 'score': 0.894798219203949}
{'label': 'non', 'score': 0.9296896457672119}
{'label': 'spec', 'score': 0.9522388577461243}
{'label': 'spec', 'score': 0.750476598739624}
{'label': 'non', 'score': 0.9525155425071716}
{'label': 'spec', 'score': 0.5556334257125854}
{'label': 'non', 'score': 0.9586845636367798}
{'label': 'non', 'score': 0.9675682783126831}
{'label': 'non', 'score': 0.8036944270133972}
{'label': 'non', 'score': 0.974850594997406}
{'label': 'spec', 'score': 0.7720035910606384}
{'label': 'non', 'score': 0.5697620511054993}
{'label': 'non', 'score': 0.7229124307632446}
{'label': 'spec', 'score': 0.5693015456199646}
{'label': 'non', 'score': 0.959693968296051}
{'label': 'non', 'score': 0.9768224954605103}
{'label': 'non', 'score': 0.9378687143325806}
{'label': 'spec', 'score': 0.6546488404273987}
{'label': 'spec', 'score': 0.6831894516944885}
{'label': 'spec', 'score': 0.8841142654418945}
{'label': 'non', 'score': 0.9016952514648438}
{'label': 'non', 'score': 0.95

In [ ]:
results_list

['non',
 'non',
 'spec',
 'spec',
 'non',
 'spec',
 'non',
 'non',
 'non',
 'non',
 'spec',
 'non',
 'non',
 'spec',
 'non',
 'non',
 'non',
 'spec',
 'spec',
 'spec',
 'non',
 'non',
 'non',
 'spec',
 'non',
 'non',
 'non',
 'non',
 'non',
 'non',
 'non',
 'non',
 'spec',
 'non',
 'non',
 'non',
 'non',
 'non',
 'spec',
 'non',
 'non',
 'non',
 'spec',
 'non',
 'spec',
 'non',
 'spec',
 'spec',
 'non',
 'non',
 'non',
 'spec',
 'non',
 'non',
 'non',
 'non',
 'non',
 'non',
 'non',
 'non',
 'non',
 'spec',
 'non',
 'non',
 'non',
 'non',
 'non',
 'non',
 'non',
 'non',
 'non',
 'non',
 'non',
 'non',
 'spec',
 'non',
 'non',
 'spec',
 'non',
 'non',
 'non',
 'non',
 'non',
 'spec',
 'spec',
 'non',
 'non',
 'spec',
 'spec',
 'spec',
 'spec',
 'non',
 'non',
 'non',
 'non',
 'non',
 'spec',
 'non',
 'spec',
 'spec',
 'non',
 'non',
 'spec',
 'spec',
 'non',
 'non',
 'non',
 'non',
 'non',
 'non',
 'non',
 'spec',
 'non',
 'non',
 'non',
 'spec',
 'non',
 'non',
 'non',
 'spec',
 'non',

In [ ]:
preds = []
for result in results_list:
  if result == 'non':
    preds.append(0)
  elif result == 'spec':
    preds.append(1)


In [ ]:
preds

[0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,


In [ ]:
from sklearn.metrics import classification_report,f1_score,confusion_matrix
print(f1_score(climate_detection_encoded_dataset['test']['label'],preds,average='macro'))

0.6508640411079435


In [ ]:
print(classification_report(climate_detection_encoded_dataset['test']['label'],preds))

              precision    recall  f1-score   support

           0       0.78      0.81      0.79       222
           1       0.53      0.49      0.51        98

    accuracy                           0.71       320
   macro avg       0.65      0.65      0.65       320
weighted avg       0.70      0.71      0.71       320



In [ ]:
print(confusion_matrix(climate_detection_encoded_dataset['test']['label'], preds))

[[179  43]
 [ 50  48]]


# Our Climate Change model - identify whether a climate-related paragraph is specific or non-specific

### dataset load

In [ ]:
!pip install transformers==4.28.0
!pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


### testing the climate detection test dataset on the climate detection model

In [ ]:
from datasets import load_dataset
climate_detection_dataset = load_dataset("climatebert/climate_specificity")

  0%|          | 0/2 [00:00<?, ?it/s]

### model loading

In [ ]:
# from transformers import AutoTokenizer, AutoModelForSequenceClassification

# climate_change_tokenizer = AutoTokenizer.from_pretrained("/content/drive/MyDrive/DS-Environment-Project/Models/climate-change-model-based-on-climate-detector-further-trained-on-paragraphs")

# climate_change_model = AutoModelForSequenceClassification.from_pretrained("/content/drive/MyDrive/DS-Environment-Project/Models/climate-change-model-based-on-climate-detector-further-trained-on-paragraphs")

In [ ]:
climate_detection_encoded_dataset = climate_detection_dataset.map(lambda t: climate_change_tokenizer(t['text'],  truncation=True), batched=True,load_from_cache_file=False)

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

Map:   0%|          | 0/320 [00:00<?, ? examples/s]

In [ ]:
# from transformers import TrainingArguments, Trainer

In [ ]:
# climate_change_arg = TrainingArguments(
#     "label",
#     learning_rate=5e-5,
#     num_train_epochs=4,
#     per_device_eval_batch_size=32,
#     per_device_train_batch_size=32,
#     seed=19
# )

In [ ]:
# climate_change_trainer = Trainer(
#     model=climate_change_model,
#     args=climate_change_arg,
#     tokenizer=climate_change_tokenizer,
#     eval_dataset=climate_detection_encoded_dataset['test']
# )

In [ ]:
# y_pred_climate_change = climate_change_trainer.predict(climate_detection_encoded_dataset['test'])

In [ ]:
# y_pred_climate_change = y_pred_climate_change.predictions

In [ ]:
# import numpy as np
# y_pred_climate_change = [np.argmax(y_pred_climate_change[i]) for i in range(0,len(y_pred_climate_change))]

In [ ]:
# y_pred_climate_change

### evaluation


In [ ]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer, pipeline
from transformers.pipelines.pt_utils import KeyDataset
import datasets
from tqdm.auto import tqdm
dataset_name = "climatebert/climate_specificity"
model_name = "c/content/drive/MyDrive/DS-Environment-Project/Models/climate-change-model-based-on-climate-detector-further-trained-on-paragraphs"
results_list = []
# If you want to use your own data, simply load them as 🤗 Datasets dataset, see https://huggingface.co/docs/datasets/loading
dataset = datasets.load_dataset(dataset_name, split="test")
tokenizer = AutoTokenizer.from_pretrained("/content/drive/MyDrive/DS-Environment-Project/Models/climate-change-model-based-on-climate-detector-further-trained-on-paragraphs",max_len=512)

model = AutoModelForSequenceClassification.from_pretrained("/content/drive/MyDrive/DS-Environment-Project/Models/climate-change-model-based-on-climate-detector-further-trained-on-paragraphs")



pipe = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer, device=0)

# See https://huggingface.co/docs/transformers/main_classes/pipelines#transformers.pipeline
for out in tqdm(pipe(KeyDataset(dataset, "text"), padding=True, truncation=True, )):
   print(out)
   results_list.append(out['label'])

  0%|          | 0/320 [00:00<?, ?it/s]

{'label': 'yes', 'score': 0.9999566078186035}
{'label': 'yes', 'score': 0.9999780654907227}
{'label': 'yes', 'score': 0.9999781847000122}
{'label': 'no', 'score': 0.997946560382843}
{'label': 'yes', 'score': 0.999976634979248}
{'label': 'yes', 'score': 0.999977707862854}
{'label': 'yes', 'score': 0.9999772310256958}
{'label': 'yes', 'score': 0.9999786615371704}
{'label': 'yes', 'score': 0.9999775886535645}
{'label': 'yes', 'score': 0.9999761581420898}
{'label': 'yes', 'score': 0.9999780654907227}
{'label': 'yes', 'score': 0.9999768733978271}
{'label': 'yes', 'score': 0.999977707862854}
{'label': 'yes', 'score': 0.9999772310256958}
{'label': 'yes', 'score': 0.9999779462814331}
{'label': 'yes', 'score': 0.9999450445175171}
{'label': 'yes', 'score': 0.9999655485153198}
{'label': 'yes', 'score': 0.9984989166259766}
{'label': 'yes', 'score': 0.9999773502349854}
{'label': 'yes', 'score': 0.9999767541885376}
{'label': 'yes', 'score': 0.9999773502349854}
{'label': 'yes', 'score': 0.99997794628

In [ ]:
results_list

['yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 'yes',
 

In [ ]:
preds = []
for result in results_list:
  if result == 'no':
    preds.append(0)
  elif result == 'yes':
    preds.append(1)


In [ ]:
preds

[1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [ ]:
from sklearn.metrics import classification_report,f1_score,confusion_matrix
print(f1_score(climate_detection_encoded_dataset['test']['label'],preds,average='macro'))

0.2732505846375247


In [ ]:
print(classification_report(climate_detection_encoded_dataset['test']['label'],preds))

              precision    recall  f1-score   support

           0       0.14      0.01      0.01       197
           1       0.37      0.95      0.54       123

    accuracy                           0.37       320
   macro avg       0.26      0.48      0.27       320
weighted avg       0.23      0.37      0.21       320



In [ ]:
print(confusion_matrix(climate_detection_encoded_dataset['test']['label'], preds))

[[  1 196]
 [  6 117]]


# Recommended classes:
0 - not climate-related <br>
1 - metrics <br>
2 - strategy <br>
3 - risk <br>
4 - governance

# ClimateBert Climate Detector model - assign a climate disclosure category to climate-related paragraphs based on the four categories of the recommendations of the Task Force on Climate-related Financial Disclosures (TCFD)

### dataset load

In [ ]:
!pip install transformers==4.28.0
!pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


### testing the climate detection test dataset on the climate detection model

In [ ]:
from datasets import load_dataset
climate_detection_dataset = load_dataset("climatebert/tcfd_recommendations")

Extracting data files:   0%|          | 0/2 [00:00<?, ?it/s]

Generating train split:   0%|          | 0/1300 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/400 [00:00<?, ? examples/s]

Dataset parquet downloaded and prepared to /root/.cache/huggingface/datasets/climatebert___parquet/climatebert--tcfd_recommendations-8f7123f770abbd61/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec. Subsequent calls will reuse this data.


  0%|          | 0/2 [00:00<?, ?it/s]

### model loading

In [ ]:
# from transformers import AutoTokenizer, AutoModelForSequenceClassification

# climate_change_tokenizer = AutoTokenizer.from_pretrained("climatebert/distilroberta-base-climate-sentiment")

# climate_change_model = AutoModelForSequenceClassification.from_pretrained("climatebert/distilroberta-base-climate-sentiment")

In [ ]:
climate_detection_encoded_dataset = climate_detection_dataset.map(lambda t: climate_change_tokenizer(t['text'],  truncation=True), batched=True,load_from_cache_file=False)

Map:   0%|          | 0/1300 [00:00<?, ? examples/s]

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

In [ ]:
# from transformers import TrainingArguments, Trainer

In [ ]:
# climate_change_arg = TrainingArguments(
#     "label",
#     learning_rate=5e-5,
#     num_train_epochs=4,
#     per_device_eval_batch_size=32,
#     per_device_train_batch_size=32,
#     seed=19
# )

In [ ]:
# climate_change_trainer = Trainer(
#     model=climate_change_model,
#     args=climate_change_arg,
#     tokenizer=climate_change_tokenizer,
#     eval_dataset=climate_detection_encoded_dataset['test']
# )

In [ ]:
# y_pred_climate_change = climate_change_trainer.predict(climate_detection_encoded_dataset['test'])

In [ ]:
# y_pred_climate_change = y_pred_climate_change.predictions

In [ ]:
# import numpy as np
# y_pred_climate_change = [np.argmax(y_pred_climate_change[i]) for i in range(0,len(y_pred_climate_change))]

In [ ]:
# y_pred_climate_change

In [ ]:
# from sklearn.metrics import classification_report,f1_score,confusion_matrix
# print(f1_score(climate_detection_encoded_dataset['test']['label'],y_pred_climate_change,average='macro'))

In [ ]:
# print(classification_report(climate_detection_encoded_dataset['test']['label'],y_pred_climate_change))

In [ ]:
# print(confusion_matrix(climate_detection_encoded_dataset['test']['label'], y_pred_climate_change))

### evaluation


In [ ]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer, pipeline
from transformers.pipelines.pt_utils import KeyDataset
import datasets
from tqdm.auto import tqdm
dataset_name = "climatebert/tcfd_recommendations"
model_name = "climatebert/distilroberta-base-climate-tcfd"
results_list = []
# If you want to use your own data, simply load them as 🤗 Datasets dataset, see https://huggingface.co/docs/datasets/loading
dataset = datasets.load_dataset(dataset_name, split="test")

model = AutoModelForSequenceClassification.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name, max_len=512)

pipe = pipeline("text-classification", model=model, tokenizer=tokenizer, device=0)

# See https://huggingface.co/docs/transformers/main_classes/pipelines#transformers.pipeline
for out in tqdm(pipe(KeyDataset(dataset, "text"), padding=True, truncation=True)):
   print(out)
   results_list.append(out['label'])

  0%|          | 0/400 [00:00<?, ?it/s]

{'label': 'strategy', 'score': 0.9009038805961609}
{'label': 'risk', 'score': 0.8909181952476501}
{'label': 'strategy', 'score': 0.9239246845245361}
{'label': 'strategy', 'score': 0.764115035533905}
{'label': 'strategy', 'score': 0.9564728140830994}
{'label': 'strategy', 'score': 0.9485288262367249}
{'label': 'strategy', 'score': 0.9600736498832703}
{'label': 'strategy', 'score': 0.9667661786079407}
{'label': 'governance', 'score': 0.8807446360588074}
{'label': 'strategy', 'score': 0.9492085576057434}
{'label': 'governance', 'score': 0.973747193813324}
{'label': 'strategy', 'score': 0.8537664413452148}
{'label': 'metrics', 'score': 0.9805870056152344}
{'label': 'risk', 'score': 0.5786815881729126}
{'label': 'strategy', 'score': 0.9406064748764038}
{'label': 'strategy', 'score': 0.7378668189048767}
{'label': 'strategy', 'score': 0.9407396912574768}
{'label': 'metrics', 'score': 0.9225163459777832}
{'label': 'strategy', 'score': 0.9183400273323059}
{'label': 'risk', 'score': 0.6676228642

In [ ]:
results_list

['strategy',
 'risk',
 'strategy',
 'strategy',
 'strategy',
 'strategy',
 'strategy',
 'strategy',
 'governance',
 'strategy',
 'governance',
 'strategy',
 'metrics',
 'risk',
 'strategy',
 'strategy',
 'strategy',
 'metrics',
 'strategy',
 'risk',
 'strategy',
 'strategy',
 'strategy',
 'metrics',
 'strategy',
 'strategy',
 'strategy',
 'strategy',
 'governance',
 'strategy',
 'strategy',
 'risk',
 'strategy',
 'strategy',
 'risk',
 'risk',
 'metrics',
 'strategy',
 'strategy',
 'strategy',
 'strategy',
 'strategy',
 'strategy',
 'strategy',
 'strategy',
 'strategy',
 'governance',
 'strategy',
 'strategy',
 'metrics',
 'governance',
 'metrics',
 'strategy',
 'strategy',
 'strategy',
 'strategy',
 'metrics',
 'risk',
 'risk',
 'metrics',
 'strategy',
 'strategy',
 'strategy',
 'strategy',
 'strategy',
 'governance',
 'governance',
 'governance',
 'metrics',
 'governance',
 'risk',
 'metrics',
 'strategy',
 'governance',
 'strategy',
 'strategy',
 'strategy',
 'strategy',
 'strategy',

In [ ]:
preds = []
for result in results_list:
  if result == 'strategy':
    preds.append(2)
  elif result == 'metrics':
    preds.append(1)
  elif result == 'risk':
    preds.append(3)
  elif result == 'governance':
    preds.append(4)
  else:
    preds.append(0)


In [ ]:
preds

[2,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 4,
 2,
 4,
 2,
 1,
 3,
 2,
 2,
 2,
 1,
 2,
 3,
 2,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 4,
 2,
 2,
 3,
 2,
 2,
 3,
 3,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 4,
 2,
 2,
 1,
 4,
 1,
 2,
 2,
 2,
 2,
 1,
 3,
 3,
 1,
 2,
 2,
 2,
 2,
 2,
 4,
 4,
 4,
 1,
 4,
 3,
 1,
 2,
 4,
 2,
 2,
 2,
 2,
 2,
 1,
 3,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 3,
 3,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 4,
 2,
 3,
 2,
 1,
 2,
 2,
 1,
 2,
 3,
 3,
 2,
 1,
 2,
 3,
 3,
 1,
 2,
 2,
 4,
 3,
 2,
 2,
 4,
 1,
 2,
 3,
 2,
 2,
 2,
 2,
 4,
 2,
 2,
 2,
 4,
 2,
 2,
 2,
 3,
 4,
 4,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 2,
 2,
 2,
 2,
 4,
 3,
 2,
 3,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 2,
 2,
 3,
 3,
 1,
 2,
 2,
 3,
 4,
 1,
 4,
 2,
 1,
 2,
 2,
 2,
 1,
 2,
 2,
 1,
 2,
 1,
 3,
 2,
 1,
 4,
 1,
 4,
 2,
 4,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 4,
 2,
 4,
 4,
 2,
 2,
 2,
 1,
 3,
 3,
 1,
 4,
 4,
 3,
 2,
 1,
 2,
 2,
 2,
 2,
 1,
 4,
 2,
 2,
 2,
 2,
 3,
 2,
 4,
 4,
 1,
 4,
 2,
 2,
 4,
 4,
 2,
 3,
 3,
 3,


In [ ]:
from sklearn.metrics import classification_report,f1_score,confusion_matrix
print(f1_score(climate_detection_encoded_dataset['test']['label'],preds,average='macro'))

0.4982667536487714


In [ ]:
print(classification_report(climate_detection_encoded_dataset['test']['label'],preds))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        80
           1       0.55      0.73      0.63        49
           2       0.69      0.84      0.76       197
           3       0.49      0.56      0.52        48
           4       0.47      0.73      0.58        26

    accuracy                           0.62       400
   macro avg       0.44      0.57      0.50       400
weighted avg       0.50      0.62      0.55       400



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
print(confusion_matrix(climate_detection_encoded_dataset['test']['label'], preds))

[[  0   9  46  13  12]
 [  0  36  10   3   0]
 [  0  17 166  10   4]
 [  0   2  14  27   5]
 [  0   1   4   2  19]]


# Our Climate Change model - assign a climate disclosure category to climate-related paragraphs based on the four categories of the recommendations of the Task Force on Climate-related Financial Disclosures (TCFD)

### dataset load

In [ ]:
!pip install transformers==4.28.0
!pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


### testing the climate detection test dataset on the climate detection model

In [ ]:
from datasets import load_dataset
climate_detection_dataset = load_dataset("climatebert/tcfd_recommendations")

  0%|          | 0/2 [00:00<?, ?it/s]

### model loading

In [ ]:
# from transformers import AutoTokenizer, AutoModelForSequenceClassification

# climate_change_tokenizer = AutoTokenizer.from_pretrained("/content/drive/MyDrive/DS-Environment-Project/Models/climate-change-model-based-on-climate-detector-further-trained-on-paragraphs")

# climate_change_model = AutoModelForSequenceClassification.from_pretrained("/content/drive/MyDrive/DS-Environment-Project/Models/climate-change-model-based-on-climate-detector-further-trained-on-paragraphs")

In [ ]:
climate_detection_encoded_dataset = climate_detection_dataset.map(lambda t: climate_change_tokenizer(t['text'],  truncation=True), batched=True,load_from_cache_file=False)

Map:   0%|          | 0/1300 [00:00<?, ? examples/s]

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

In [ ]:
# from transformers import TrainingArguments, Trainer

In [ ]:
# climate_change_arg = TrainingArguments(
#     "label",
#     learning_rate=5e-5,
#     num_train_epochs=4,
#     per_device_eval_batch_size=32,
#     per_device_train_batch_size=32,
#     seed=19
# )

In [ ]:
# climate_change_trainer = Trainer(
#     model=climate_change_model,
#     args=climate_change_arg,
#     tokenizer=climate_change_tokenizer,
#     eval_dataset=climate_detection_encoded_dataset['test']
# )

In [ ]:
# y_pred_climate_change = climate_change_trainer.predict(climate_detection_encoded_dataset['test'])

You're using a RobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.


In [ ]:
# y_pred_climate_change = y_pred_climate_change.predictions

In [ ]:
# import numpy as np
# y_pred_climate_change = [np.argmax(y_pred_climate_change[i]) for i in range(0,len(y_pred_climate_change))]

In [ ]:
# y_pred_climate_change

[1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,


In [ ]:
# from sklearn.metrics import classification_report,f1_score,confusion_matrix
# print(f1_score(climate_detection_encoded_dataset['test']['label'],y_pred_climate_change))

0.973561430793157


In [ ]:
# print(classification_report(climate_detection_encoded_dataset['test']['label'],y_pred_climate_change))

              precision    recall  f1-score   support

           0       0.91      0.88      0.89        80
           1       0.97      0.98      0.97       320

    accuracy                           0.96       400
   macro avg       0.94      0.93      0.93       400
weighted avg       0.96      0.96      0.96       400



In [ ]:
# print(confusion_matrix(climate_detection_encoded_dataset['test']['label'], y_pred_climate_change))

[[ 70  10]
 [  7 313]]


### evaluation


In [ ]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer, pipeline
from transformers.pipelines.pt_utils import KeyDataset
import datasets
from tqdm.auto import tqdm
dataset_name = "climatebert/tcfd_recommendations"
model_name = "c/content/drive/MyDrive/DS-Environment-Project/Models/climate-change-model-based-on-climate-detector-further-trained-on-paragraphs"
results_list = []
# If you want to use your own data, simply load them as 🤗 Datasets dataset, see https://huggingface.co/docs/datasets/loading
dataset = datasets.load_dataset(dataset_name, split="test")
tokenizer = AutoTokenizer.from_pretrained("/content/drive/MyDrive/DS-Environment-Project/Models/climate-change-model-based-on-climate-detector-further-trained-on-paragraphs",max_len=512)

model = AutoModelForSequenceClassification.from_pretrained("/content/drive/MyDrive/DS-Environment-Project/Models/climate-change-model-based-on-climate-detector-further-trained-on-paragraphs", num_labels=5,ignore_mismatched_sizes=True)



pipe = pipeline("text-classification", model=model, tokenizer=tokenizer, device=0)

# See https://huggingface.co/docs/transformers/main_classes/pipelines#transformers.pipeline
for out in tqdm(pipe(KeyDataset(dataset, "text"), padding=True, truncation=True, )):
   print(out)
   results_list.append(out['label'])

Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at /content/drive/MyDrive/DS-Environment-Project/Models/climate-change-model-based-on-climate-detector-further-trained-on-paragraphs and are newly initialized because the shapes did not match:
- classifier.out_proj.weight: found shape torch.Size([2, 768]) in the checkpoint and torch.Size([5, 768]) in the model instantiated
- classifier.out_proj.bias: found shape torch.Size([2]) in the checkpoint and torch.Size([5]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


  0%|          | 0/400 [00:00<?, ?it/s]

{'label': 'LABEL_4', 'score': 0.3125116229057312}
{'label': 'LABEL_4', 'score': 0.3132303059101105}
{'label': 'LABEL_4', 'score': 0.30929604172706604}
{'label': 'LABEL_1', 'score': 0.34147387742996216}
{'label': 'LABEL_4', 'score': 0.31040021777153015}
{'label': 'LABEL_4', 'score': 0.3152984380722046}
{'label': 'LABEL_4', 'score': 0.31293442845344543}
{'label': 'LABEL_4', 'score': 0.29724568128585815}
{'label': 'LABEL_4', 'score': 0.31250786781311035}
{'label': 'LABEL_4', 'score': 0.3116084933280945}
{'label': 'LABEL_1', 'score': 0.2896004319190979}
{'label': 'LABEL_4', 'score': 0.31020933389663696}
{'label': 'LABEL_4', 'score': 0.31454357504844666}
{'label': 'LABEL_1', 'score': 0.32322096824645996}
{'label': 'LABEL_4', 'score': 0.31396234035491943}
{'label': 'LABEL_1', 'score': 0.2943829894065857}
{'label': 'LABEL_4', 'score': 0.3173670172691345}
{'label': 'LABEL_4', 'score': 0.31275367736816406}
{'label': 'LABEL_4', 'score': 0.3124721646308899}
{'label': 'LABEL_4', 'score': 0.3071610

In [ ]:
results_list

['LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_1',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_1',
 'LABEL_4',
 'LABEL_4',
 'LABEL_1',
 'LABEL_4',
 'LABEL_1',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_1',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_1',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_1',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_1',
 'LABEL_4',
 'LABEL_4',
 'LABEL_4',
 'LABEL_1',
 'LABEL_4',
 'LABEL_4',
 'LABEL_1',
 'LA

In [ ]:
preds = []
for result in results_list:
  if result == 'LABEL_2':
    preds.append(2)
  elif result == 'LABEL_1':
    preds.append(1)
  elif result == 'LABEL_3':
    preds.append(3)
  elif result == 'LABEL_4':
    preds.append(4)
  else:
    preds.append(0)


In [ ]:
preds

[4,
 4,
 4,
 1,
 4,
 4,
 4,
 4,
 4,
 4,
 1,
 4,
 4,
 1,
 4,
 1,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 1,
 4,
 4,
 4,
 1,
 4,
 4,
 4,
 4,
 1,
 4,
 4,
 4,
 1,
 4,
 4,
 4,
 1,
 4,
 4,
 1,
 4,
 1,
 4,
 4,
 4,
 4,
 4,
 1,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 1,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 1,
 3,
 4,
 4,
 4,
 4,
 4,
 1,
 4,
 4,
 4,
 4,
 1,
 1,
 4,
 1,
 4,
 1,
 4,
 4,
 1,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 1,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 1,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 1,
 4,
 4,
 4,
 1,
 4,
 1,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 1,
 4,
 4,
 4,
 4,
 4,
 3,
 4,
 4,
 1,
 4,
 1,
 1,
 4,
 1,
 4,
 4,
 4,
 4,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 1,
 1,
 4,
 1,
 4,
 1,
 1,
 4,
 4,
 4,
 4,
 1,
 4,
 1,
 4,
 1,
 4,
 4,
 1,
 4,
 1,
 4,
 1,
 4,
 4,
 4,
 4,
 4,
 4,
 1,
 4,
 4,
 4,
 4,


In [ ]:
from sklearn.metrics import classification_report,f1_score,confusion_matrix
print(f1_score(climate_detection_encoded_dataset['test']['label'],preds,average='macro'))

0.03763996554694229


In [ ]:
print(classification_report(climate_detection_encoded_dataset['test']['label'],preds))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        80
           1       0.00      0.00      0.00        49
           2       0.00      0.00      0.00       197
           3       0.17      0.02      0.04        48
           4       0.08      1.00      0.15        26

    accuracy                           0.07       400
   macro avg       0.05      0.20      0.04       400
weighted avg       0.03      0.07      0.01       400



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
print(confusion_matrix(climate_detection_encoded_dataset['test']['label'], preds))

[[  0  70   0   0  10]
 [  0   0   0   2  47]
 [  0   6   0   3 188]
 [  0   0   0   1  47]
 [  0   0   0   0  26]]
